ev_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: oilgylj-qt75521
      user: SNOWFLAKEDEMO
      role: ACCOUNTADMIN
      database: EV_PIPELINE
      warehouse: EV_WH
      schema: GOLD
      threads: 4
      authenticator: snowflake
