-- ============================================================
-- ADMIN SCHEMA: Governance (RBAC, Masking, Tags)
-- ============================================================
-- Design Decision: Centralized governance in ADMIN schema
--   - Tags, masking policies, and RBAC definitions in one place
--   - Separation from data schemas
--   - Principle: Governance inherits to AI — Cortex Analyst
--     queries respect RBAC automatically
-- ============================================================

USE DATABASE EV_PIPELINE;
CREATE SCHEMA IF NOT EXISTS EV_PIPELINE.ADMIN;
USE SCHEMA ADMIN;

-- ==================
-- ROLES
-- ==================
CREATE ROLE IF NOT EXISTS DOL_ANALYST;
CREATE ROLE IF NOT EXISTS UTILITY_READER;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;

-- DOL_ANALYST: Full read on Gold layer
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE DOL_ANALYST;
GRANT USAGE ON SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA EV_PIPELINE.GOLD TO ROLE DOL_ANALYST;

-- UTILITY_READER: Only shared views (restricted)
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE UTILITY_READER;
GRANT USAGE ON SCHEMA EV_PIPELINE.GOLD TO ROLE UTILITY_READER;
GRANT SELECT ON VIEW EV_PIPELINE.GOLD.SHARED_UTILITY_DEMAND TO ROLE UTILITY_READER;
GRANT SELECT ON VIEW EV_PIPELINE.GOLD.SHARED_EV_COUNTY_TRENDS TO ROLE UTILITY_READER;

-- DATA_ENGINEER: All schemas (pipeline maintenance)
GRANT USAGE ON DATABASE EV_PIPELINE TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EV_PIPELINE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.BRONZE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.SILVER TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.GOLD TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA EV_PIPELINE.AUDIT TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA EV_PIPELINE.AUDIT TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA EV_PIPELINE.AUDIT TO ROLE DATA_ENGINEER;

-- ==================
-- OBJECT TAGS
-- ==================
CREATE OR REPLACE TAG ADMIN.PII COMMENT = 'Personally Identifiable Information';
CREATE OR REPLACE TAG ADMIN.GEOGRAPHIC COMMENT = 'Geographic/Location data';
CREATE OR REPLACE TAG ADMIN.FINANCIAL COMMENT = 'Financial/Pricing data';

-- Apply tags to the Gold business-facing columns (where consumers query)
ALTER DYNAMIC TABLE GOLD.DIM_LOCATION MODIFY COLUMN ZIP_CODE  SET TAG ADMIN.PII = 'zip_code';
ALTER DYNAMIC TABLE GOLD.DIM_LOCATION MODIFY COLUMN COUNTY    SET TAG ADMIN.GEOGRAPHIC = 'county';
ALTER DYNAMIC TABLE GOLD.DIM_VEHICLE  MODIFY COLUMN BASE_MSRP SET TAG ADMIN.FINANCIAL = 'msrp';

-- ==================
-- DYNAMIC MASKING
-- ==================
-- Mask zip codes: UTILITY_READER sees only first 3 digits (regional, not exact)
CREATE OR REPLACE MASKING POLICY ADMIN.ZIP_MASK AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DOL_ANALYST', 'DATA_ENGINEER') THEN val
        ELSE LEFT(val, 3) || '**'
    END;

-- Apply to the Gold business-facing dimension (where analysts/consumers query)
ALTER DYNAMIC TABLE GOLD.DIM_LOCATION 
    MODIFY COLUMN ZIP_CODE SET MASKING POLICY ADMIN.ZIP_MASK;

-- ==================
-- VERIFY
-- ==================
SHOW ROLES;
SHOW MASKING POLICIES IN SCHEMA ADMIN;
SHOW TAGS IN SCHEMA ADMIN;
